/**
 * Bundled brand icons for the connector catalog (fetched at build time —
 * the app never calls a favicon service at runtime). Falls back to the
 * letter tile for anything unmapped: custom servers, new catalog entries.
 */
export const MCP_LOGOS: Record<string, number> = {
  "airtable": require("../../assets/connectors/airtable.png"),
  "algolia": require("../../assets/connectors/algolia.png"),
  "alltrails": require("../../assets/connectors/alltrails.png"),
  "amplitude": require("../../assets/connectors/amplitude.png"),
  "asana": require("../../assets/connectors/asana.png"),
  "atlassian": require("../../assets/connectors/atlassian.png"),
  "attio": require("../../assets/connectors/attio.png"),
  "aws-knowledge": require("../../assets/connectors/aws-knowledge.png"),
  "betterstack": require("../../assets/connectors/betterstack.png"),
  "buildkite": require("../../assets/connectors/buildkite.png"),
  "calendly": require("../../assets/connectors/calendly.png"),
  "canva": require("../../assets/connectors/canva.png"),
  "circleci": require("../../assets/connectors/circleci.png"),
  "clickup": require("../../assets/connectors/clickup.png"),
  "close": require("../../assets/connectors/close.png"),
  "cloudflare": require("../../assets/connectors/cloudflare.png"),
  "cloudinary": require("../../assets/connectors/cloudinary.png"),
  "comfy-cloud": require("../../assets/connectors/comfy-cloud.png"),
  "context7": require("../../assets/connectors/context7.png"),
  "craft": require("../../assets/connectors/craft.png"),
  "datadog": require("../../assets/connectors/datadog.png"),
  "deepwiki": require("../../assets/connectors/deepwiki.png"),
  "dropbox": require("../../assets/connectors/dropbox.png"),
  "figma": require("../../assets/connectors/figma.png"),
  "fireflies": require("../../assets/connectors/fireflies.png"),
  "gamma": require("../../assets/connectors/gamma.png"),
  "gitlab": require("../../assets/connectors/gitlab.png"),
  "globalping": require("../../assets/connectors/globalping.png"),
  "grafana": require("../../assets/connectors/grafana.png"),
  "hugging_face": require("../../assets/connectors/hugging_face.png"),
  "indeed": require("../../assets/connectors/indeed.png"),
  "intercom": require("../../assets/connectors/intercom.png"),
  "kiwi": require("../../assets/connectors/kiwi.png"),
  "klaviyo": require("../../assets/connectors/klaviyo.png"),
  "linear": require("../../assets/connectors/linear.png"),
  "microsoft-learn": require("../../assets/connectors/microsoft-learn.png"),
  "miro": require("../../assets/connectors/miro.png"),
  "mixpanel": require("../../assets/connectors/mixpanel.png"),
  "monday": require("../../assets/connectors/monday.png"),
  "motherduck": require("../../assets/connectors/motherduck.png"),
  "n8n-official": require("../../assets/connectors/n8n-official.png"),
  "neon": require("../../assets/connectors/neon.png"),
  "netlify": require("../../assets/connectors/netlify.png"),
  "notion": require("../../assets/connectors/notion.png"),
  "paypal": require("../../assets/connectors/paypal.png"),
  "plaid": require("../../assets/connectors/plaid.png"),
  "postman": require("../../assets/connectors/postman.png"),
  "prisma-postgres": require("../../assets/connectors/prisma-postgres.png"),
  "railway": require("../../assets/connectors/railway.png"),
  "robinhood": require("../../assets/connectors/robinhood.png"),
  "semgrep": require("../../assets/connectors/semgrep.png"),
  "sentry": require("../../assets/connectors/sentry.png"),
  "square": require("../../assets/connectors/square.png"),
  "strava": require("../../assets/connectors/strava.png"),
  "stripe": require("../../assets/connectors/stripe.png"),
  "supabase": require("../../assets/connectors/supabase.png"),
  "todoist": require("../../assets/connectors/todoist.png"),
  "trivago": require("../../assets/connectors/trivago.png"),
  "twelve-data": require("../../assets/connectors/twelve-data.png"),
  "twilio-docs": require("../../assets/connectors/twilio-docs.png"),
  "unreal-engine": require("../../assets/connectors/unreal-engine.png"),
  "vercel": require("../../assets/connectors/vercel.png"),
  "webflow": require("../../assets/connectors/webflow.png"),
  "wolfram": require("../../assets/connectors/wolfram.png"),
  "wordpress-com": require("../../assets/connectors/wordpress-com.png"),
}
